"""
Lupine Systems V0 — Data Models
All V0 data primitives: movement_request, route_option, decision_score,
execution_state, evidence_log.
"""
from pydantic import BaseModel, Field
from typing import Optional
from datetime import datetime
from enum import Enum
import uuid


# ── Enums ──

class Urgency(str, Enum):
    low = "low"
    normal = "normal"
    high = "high"
    critical = "critical"


class ExecutionStatus(str, Enum):
    initiated = "initiated"
    scored = "scored"
    route_selected = "route_selected"
    executing = "executing"
    completed = "completed"
    failed = "failed"


# ── Movement Request ──

class MovementRequest(BaseModel):
    """Input from user: what needs to move."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    amount: float
    from_currency: str
    to_currency: str
    urgency: Urgency = Urgency.normal
    created_at: datetime = Field(default_factory=datetime.utcnow)


# ── Route Option ──

class RouteOption(BaseModel):
    """A single candidate route generated by Aiva-lite."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str                          # e.g. "Fast Route", "Cheap Route", "Balanced Route"
    corridor: str                      # e.g. "AUD → SGD direct" or "AUD → USD → SGD"
    estimated_time_hours: float        # predicted settlement time
    estimated_cost_bps: float          # cost in basis points
    reliability_score: float           # 0.0 to 1.0
    speed_score: float = 0.0           # computed by scorer
    cost_score: float = 0.0            # computed by scorer
    composite_score: float = 0.0       # final weighted score


# ── Decision Score ──

class DecisionScore(BaseModel):
    """The scoring breakdown and selection rationale."""
    request_id: str
    route_scores: list[RouteOption]
    selected_route_id: str
    selected_route_name: str
    rationale: str                     # human-readable explanation
    weights_used: dict                 # {"speed": 0.5, "cost": 0.2, "reliability": 0.3}
    scored_at: datetime = Field(default_factory=datetime.utcnow)


# ── Execution State ──

class ExecutionState(BaseModel):
    """Rail-lite state machine tracking."""
    request_id: str
    route_id: str
    status: ExecutionStatus = ExecutionStatus.initiated
    state_history: list[dict] = Field(default_factory=list)
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None


# ── Evidence Log Entry ──

class EvidenceEntry(BaseModel):
    """A single evidence record in the Cloked-lite chain."""
    sequence: int
    event_type: str                    # e.g. "request_created", "routes_generated", "route_scored"
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    data_hash: str                     # SHA-256 of the event data
    previous_hash: str = ""            # chain link
    payload: dict                      # the actual event data


class EvidenceLog(BaseModel):
    """Full evidence chain for a movement request."""
    request_id: str
    entries: list[EvidenceEntry] = Field(default_factory=list)
    chain_valid: bool = True
